# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170805_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=9.99, max_digits=15, null=True),
        ),
    ]
