# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('billing', 'billing'), ('Shipping', 'Shipping')], default='shipping', max_length=120),
            preserve_default=False,
        ),
    ]
